---
# Codacy Quality Configuration for Fleet Management System

engines:
  eslint:
    enabled: true
    exclude_paths:
      - "node_modules/**"
      - "dist/**"
      - "build/**"
      - "coverage/**"

  typescript:
    enabled: true
    exclude_paths:
      - "node_modules/**"
      - "dist/**"

  security:
    enabled: true

coverage:
  enabled: true
  min: 60
  exclude_paths:
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.spec.ts"
    - "**/*.spec.tsx"
    - "**/tests/**"
    - "**/e2e/**"

duplication:
  enabled: true
  min_tokens: 50
  max: 7

complexity:
  enabled: true
  max: 10

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "coverage/**"
  - "public/**"
  - ".husky/**"
  - ".github/**"
  - "playwright-report/**"
  - "test-results/**"

test_patterns:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/tests/**"
  - "**/e2e/**"
