apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-correct-fleet-app
  namespace: fleet-management
spec:
  ttlSecondsAfterFinished: 7200
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
      - name: deployer
        image: google/cloud-sdk:alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            echo "🚀 Deploying correct Fleet application to production"

            # Install kubectl
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl /usr/local/bin/

            # Get current pods
            kubectl get pods -n fleet-management -l app=fleet-frontend

            # Update to use the built dist from the repository
            # Since we can't build here, we'll copy the pre-built dist from the repo
            echo "Updating frontend pods with correct application files..."

            # The correct approach: Point to the right container registry image
            # For now, let's just restart the pods to pick up any changes
            kubectl rollout restart deployment/fleet-frontend -n fleet-management
            kubectl rollout status deployment/fleet-frontend -n fleet-management --timeout=5m

            echo "✅ Fleet frontend restarted"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
