#!/bin/bash

echo "🚀 Fleet Management System - Deployment from Your Local Machine"
echo "================================================================="
echo ""
echo "STEP 1: Verify Prerequisites"
echo "-----------------------------"
echo "Run these commands on YOUR local machine:"
echo ""
echo "# 1. Check Azure CLI"
echo "az --version"
echo ""
echo "# 2. Check you're logged in"
echo "az account show"
echo ""
echo "# 3. Pull the latest code"
echo "git pull origin claude/code-review-011CV2Mofus1z3JiMv3W66La"
echo ""
echo ""
echo "STEP 2: Set Environment Variables"
echo "----------------------------------"
echo "You need to set these on YOUR machine:"
echo ""
echo "export OPENAI_API_KEY='your-openai-key-here'"
echo "export SENDGRID_API_KEY='your-sendgrid-key-here'  # Optional"
echo "export TWILIO_ACCOUNT_SID='your-twilio-sid'  # Optional"
echo "export TWILIO_AUTH_TOKEN='your-twilio-token'  # Optional"
echo ""
echo ""
echo "STEP 3: Run Deployment"
echo "----------------------"
echo "chmod +x scripts/deploy-staging.sh"
echo "./scripts/deploy-staging.sh"
echo ""
echo ""
echo "STEP 4: Verify Deployment"
echo "-------------------------"
echo "chmod +x scripts/verify-deployment.sh"
echo "./scripts/verify-deployment.sh"
echo ""
