apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fleet-tls-cert
  namespace: fleet-management
spec:
  secretName: fleet-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - fleet.capitaltechalliance.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-main
  namespace: fleet-management
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - fleet.capitaltechalliance.com
    secretName: fleet-tls-secret
  rules:
  - host: fleet.capitaltechalliance.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fleet-frontend
            port:
              number: 80
