apiVersion: v1
kind: ConfigMap
metadata:
  name: remediation-scripts
  namespace: fleet-management
data:
  frontend-worker.sh: |
    #!/bin/bash
    # Frontend Issues Worker
    cd /workspace
    npm install

    # Break down monolithic components
    npx ts-node scripts/break-down-components.ts

    # Extract code duplication
    npx ts-node scripts/extract-common-utils.ts

    # Reorganize folder structure
    npx ts-node scripts/reorganize-folders.ts

    # Enable strict mode
    echo '{"compilerOptions":{"strict":true,"noEmitOnError":true}}' > tsconfig.strict.json

    # Run eslint fixes
    npx eslint --fix src/

    echo "Frontend worker complete"

  backend-worker.sh: |
    #!/bin/bash
    # Backend Issues Worker
    cd /workspace/api
    npm install

    # Install Drizzle ORM
    npm install drizzle-orm drizzle-kit
    npx drizzle-kit generate

    # Install rate limiting
    npm install express-rate-limit

    # Install Winston logger
    npm install winston

    # Install React Compiler
    npm install babel-plugin-react-compiler

    # Run TypeScript compilation
    npx tsc --noEmit

    echo "Backend worker complete"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: remediation-frontend-1
  namespace: fleet-management
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: node:20-alpine
        command: ["/bin/sh", "/scripts/frontend-worker.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: workspace
          mountPath: /workspace
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: scripts
        configMap:
          name: remediation-scripts
          defaultMode: 0755
      - name: workspace
        emptyDir: {}
      initContainers:
      - name: clone-repo
        image: alpine/git
        command:
        - sh
        - -c
        - |
          git clone https://github.com/asmortongpt/Fleet.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace

---
apiVersion: batch/v1
kind: Job
metadata:
  name: remediation-backend-1
  namespace: fleet-management
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: worker
        image: node:20-alpine
        command: ["/bin/sh", "/scripts/backend-worker.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: workspace
          mountPath: /workspace
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: scripts
        configMap:
          name: remediation-scripts
          defaultMode: 0755
      - name: workspace
        emptyDir: {}
      initContainers:
      - name: clone-repo
        image: alpine/git
        command:
        - sh
        - -c
        - |
          git clone https://github.com/asmortongpt/Fleet.git /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
