apiVersion: batch/v1
kind: Job
metadata:
  labels:
    category: low-priority-&-cleanup
    worker: k8s-worker-12
    zero-simulation: 'true'
  name: k8s-worker-12
  namespace: honest-orchestration
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        worker: k8s-worker-12
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - pip install --no-cache-dir requests pyyaml && python3 /scripts/k8s-worker-script.py
        env:
        - name: LLM_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: llm-endpoint
              name: orchestrator-config
        - name: WORKER_ID
          value: k8s-worker-12
        image: python:3.11-slim
        name: honest-orchestrator
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /scripts
          name: scripts
        - mountPath: /workspace
          name: workspace
      restartPolicy: OnFailure
      volumes:
      - configMap:
          name: orchestrator-config
        name: config
      - configMap:
          name: worker-scripts
        name: scripts
      - emptyDir: {}
        name: workspace
  ttlSecondsAfterFinished: 86400
