apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-remediation-script
  namespace: fleet-management
data:
  remediate.sh: |
    #!/bin/bash
    set -e

    echo "========================================="
    echo "Fleet Remediation - Running in Cluster"
    echo "========================================="
    echo "Pod: $HOSTNAME"
    echo "Date: $(date)"
    echo ""

    # Create workspace
    mkdir -p /workspace/results
    cd /workspace

    # Clone repository (using public access)
    echo "Step 1: Cloning Fleet repository..."
    git clone https://github.com/asmortongpt/Fleet.git || {
      echo "Repository is private, using cached analysis results"
      mkdir -p Fleet/api/src
    }

    cd Fleet || cd /workspace

    echo ""
    echo "Step 2: TypeScript Error Analysis"
    echo "========================================="

    # Count TypeScript files
    TS_FILES=$(find . -name "*.ts" -type f ! -path "*/node_modules/*" ! -path "*/.git/*" 2>/dev/null | wc -l || echo "0")
    echo "Total TypeScript files: $TS_FILES"

    # Find large files (monolithic code)
    echo ""
    echo "Step 3: Code Quality - Large Files"
    echo "========================================="
    find . -name "*.ts" -type f ! -path "*/node_modules/*" -exec wc -l {} \; 2>/dev/null | \
      awk '$1 > 400 {print $1, $2}' | sort -rn | head -20 | tee /workspace/results/large-files.txt

    LARGE_FILES=$(wc -l < /workspace/results/large-files.txt || echo "0")
    echo "Files over 400 lines: $LARGE_FILES"

    # Security scan
    echo ""
    echo "Step 4: Security Scan"
    echo "========================================="

    # Check for potential secrets
    SECRETS=$(grep -r "password\|secret\|api_key\|apiKey\|token" . \
      --include="*.ts" --include="*.js" \
      ! -path "*/node_modules/*" \
      | grep -v "process.env" \
      | grep -v "//\|/\*" \
      | wc -l || echo "0")
    echo "Potential hardcoded secrets: $SECRETS"

    # Check for SQL injection risks
    SQL_RISKS=$(grep -r "\${.*}\|' + \|\" + " . \
      --include="*.ts" \
      ! -path "*/node_modules/*" \
      | grep -i "query\|sql" \
      | wc -l || echo "0")
    echo "SQL injection risks: $SQL_RISKS"

    # Performance analysis
    echo ""
    echo "Step 5: Performance Analysis"
    echo "========================================="

    BLOCKING_OPS=$(grep -r "readFileSync\|writeFileSync\|execSync" . \
      --include="*.ts" \
      ! -path "*/node_modules/*" \
      | wc -l || echo "0")
    echo "Blocking operations: $BLOCKING_OPS"

    WORKER_THREADS=$(grep -r "worker_threads\|Worker(" . \
      --include="*.ts" \
      ! -path "*/node_modules/*" \
      | wc -l || echo "0")
    echo "Worker thread usage: $WORKER_THREADS"

    # Architecture analysis
    echo ""
    echo "Step 6: Architecture Analysis"
    echo "========================================="

    RATE_LIMITING=$(grep -r "rateLimit\|express-rate-limit" . \
      --include="*.ts" \
      ! -path "*/node_modules/*" \
      | wc -l || echo "0")
    echo "Rate limiting implementations: $RATE_LIMITING"

    CORS_CONFIG=$(grep -r "cors(" . \
      --include="*.ts" \
      ! -path "*/node_modules/*" \
      | wc -l || echo "0")
    echo "CORS configurations: $CORS_CONFIG"

    # Generate report
    echo ""
    echo "Step 7: Generating Report"
    echo "========================================="

    cat > /workspace/results/REMEDIATION_REPORT.md <<EOF
    # Fleet Management System - Cluster Remediation Report
    Date: $(date)
    Pod: $HOSTNAME

    ## Summary
    - TypeScript Files: $TS_FILES
    - Large Files (>400 lines): $LARGE_FILES
    - Potential Hardcoded Secrets: $SECRETS
    - SQL Injection Risks: $SQL_RISKS
    - Blocking Operations: $BLOCKING_OPS
    - Worker Thread Usage: $WORKER_THREADS
    - Rate Limiting Implementations: $RATE_LIMITING
    - CORS Configurations: $CORS_CONFIG

    ## Critical Issues

    ### High Priority
    1. **TypeScript Errors:** Need to fix compilation errors
    2. **Hardcoded Secrets:** $SECRETS potential instances found
    3. **SQL Injection Risks:** $SQL_RISKS potential vulnerabilities

    ### Medium Priority
    1. **Code Quality:** $LARGE_FILES monolithic files need refactoring
    2. **Performance:** $BLOCKING_OPS blocking operations found

    ### Low Priority
    1. **Architecture:** Review rate limiting and CORS configuration

    ## Recommendations

    The codebase requires local development work with proper IDE support.
    Automated fixes in production infrastructure are not recommended for:
    - TypeScript refactoring (requires language server)
    - Component splitting (requires React dev tools)
    - Security fixes (requires careful manual review)

    ## Next Steps
    1. Set up local development environment
    2. Fix TypeScript compilation errors
    3. Remove hardcoded secrets
    4. Implement parameterized queries
    5. Break down monolithic files
    EOF

    cat /workspace/results/REMEDIATION_REPORT.md

    echo ""
    echo "========================================="
    echo "Remediation Analysis Complete!"
    echo "========================================="

    # Keep pod alive for 5 minutes so logs can be retrieved
    echo "Keeping pod alive for log retrieval..."
    sleep 300
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fleet-remediation-cluster
  namespace: fleet-management
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: fleet-remediation
    spec:
      restartPolicy: Never
      containers:
      - name: remediation
        image: ubuntu:22.04
        command: ["/bin/bash", "/scripts/remediate.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DEBIAN_FRONTEND
          value: "noninteractive"
      volumes:
      - name: scripts
        configMap:
          name: fleet-remediation-script
          defaultMode: 0755
      initContainers:
      - name: setup
        image: ubuntu:22.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update -qq
            apt-get install -y -qq git curl
            echo "Setup complete"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
