apiVersion: v1
kind: Service
metadata:
  name: ollama-llm-service
  namespace: honest-orchestration
spec:
  ports:
  - port: 11434
    protocol: TCP
    targetPort: 11434
  selector:
    app: ollama-llm
  type: ClusterIP
