---
# External Secrets Operator - SecretStore Configuration
# This configures the connection to Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: fleet-management
spec:
  provider:
    azurekv:
      # The Azure Key Vault URL - update this after running setup-azure-keyvault.sh
      vaultUrl: "https://YOUR_KEYVAULT_NAME.vault.azure.net"
      tenantId: "YOUR_TENANT_ID"
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          key: client-id
        clientSecret:
          name: azure-sp-credentials
          key: client-secret

---
# Kubernetes Secret containing Service Principal credentials
# This secret needs to be created manually after running setup-azure-keyvault.sh
# kubectl create secret generic azure-sp-credentials \
#   --from-literal=client-id='YOUR_CLIENT_ID' \
#   --from-literal=client-secret='YOUR_CLIENT_SECRET' \
#   -n fleet-management
apiVersion: v1
kind: Secret
metadata:
  name: azure-sp-credentials
  namespace: fleet-management
type: Opaque
stringData:
  # REPLACE THESE VALUES after running setup-azure-keyvault.sh
  # Get these from the script output or from Key Vault
  client-id: "REPLACE_WITH_SP_CLIENT_ID"
  client-secret: "REPLACE_WITH_SP_CLIENT_SECRET"

---
# External Secret for Database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-database-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-database-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: db-username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: db-password
  - secretKey: DB_HOST
    remoteRef:
      key: db-host
  - secretKey: DB_PORT
    remoteRef:
      key: db-port
  - secretKey: DB_NAME
    remoteRef:
      key: db-name

---
# External Secret for Application secrets (JWT, encryption, etc.)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-app-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: jwt-secret
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: encryption-key

---
# External Secret for Redis
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-redis-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-redis-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: redis-password

---
# External Secret for AI Services API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-ai-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-ai-secrets
    creationPolicy: Owner
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: openai-api-key
  - secretKey: CLAUDE_API_KEY
    remoteRef:
      key: claude-api-key
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: gemini-api-key

---
# External Secret for Azure Storage
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-storage-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-storage-secrets
    creationPolicy: Owner
  data:
  - secretKey: AZURE_STORAGE_CONNECTION_STRING
    remoteRef:
      key: azure-storage-connection-string

---
# External Secret for Optional Third-party Services
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fleet-thirdparty-secrets
  namespace: fleet-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: fleet-thirdparty-secrets
    creationPolicy: Owner
  data:
  - secretKey: SENDGRID_API_KEY
    remoteRef:
      key: sendgrid-api-key
  - secretKey: TWILIO_AUTH_TOKEN
    remoteRef:
      key: twilio-auth-token
  - secretKey: MAPBOX_API_KEY
    remoteRef:
      key: mapbox-api-key
  - secretKey: SAMSARA_API_TOKEN
    remoteRef:
      key: samsara-api-token
