Below are Kubernetes manifests tailored for a production environment, covering the requirements listed. Each component is designed with security, reliability, and scalability in mind.

### 1. Backend API Deployment with HPA

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: your-backend-api-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          readOnlyRootFilesystem: true
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-api
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
```

### 2. WebSocket Server Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: your-websocket-server-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        securityContext:
          runAsUser: 1001
          runAsGroup: 3001
          readOnlyRootFilesystem: true
```

### 3. Python ML Worker Deployment (GPU-enabled)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-worker
  template:
    metadata:
      labels:
        app: ml-worker
    spec:
      containers:
      - name: ml-worker
        image: your-ml-worker-image
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "500m"
            memory: "4Gi"
        securityContext:
          runAsUser: 1002
          runAsGroup: 3002
          readOnlyRootFilesystem: true
```

### 4. Redis Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
        securityContext:
          runAsUser: 1003
          runAsGroup: 3003
          readOnlyRootFilesystem: true
```

### 5. NGINX Ingress Controller

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "yourdomain.com"
    secretName: yourdomain-tls
  rules:
  - host: "yourdomain.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-api
            port:
              number: 8080
```

### 6. TLS Certificates with Let's Encrypt

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yourdomain-tls
spec:
  secretName: yourdomain-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - yourdomain.com
```

### 7. ConfigMaps for Environment Variables

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-config
data:
  DATABASE_URL: "jdbc:mysql://your-database-url"
  LOG_LEVEL: "INFO"
```

### 8. Secrets for Sensitive Data

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secrets
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded
```

### 9. PersistentVolumeClaims for Storage

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

### 10. Services (ClusterIP, LoadBalancer)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-api
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: websocket-server
```

### 11. NetworkPolicies for Security

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-api-network-policy
spec:
  podSelector:
    matchLabels:
      app: backend-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
```

### 12. PodDisruptionBudgets for Reliability

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: backend-api
```

These manifests should be tailored further based on specific application requirements and the Kubernetes cluster configuration. Always ensure that your cluster has the necessary CRDs (like for cert-manager and NGINX ingress) and RBAC permissions configured.