export const TYPES = {
  // Controllers
  VehicleController: Symbol.for("VehicleController"),
  DriverController: Symbol.for("DriverController"),
  MaintenanceController: Symbol.for("MaintenanceController"),
  FacilityController: Symbol.for("FacilityController"),
  TelemetryController: Symbol.for("TelemetryController"),
  WorkOrderController: Symbol.for("WorkOrderController"),
  IncidentController: Symbol.for("IncidentController"),
  InspectionController: Symbol.for("InspectionController"),
  DocumentController: Symbol.for("DocumentController"),

  // Services
  VehicleService: Symbol.for("VehicleService"),
  DriverService: Symbol.for("DriverService"),
  MaintenanceService: Symbol.for("MaintenanceService"),
  FacilityService: Symbol.for("FacilityService"),
  TelemetryService: Symbol.for("TelemetryService"),
  WorkOrderService: Symbol.for("WorkOrderService"),
  IncidentService: Symbol.for("IncidentService"),
  InspectionService: Symbol.for("InspectionService"),
  DocumentService: Symbol.for("DocumentService"),

  // Repositories
  VehicleRepository: Symbol.for("VehicleRepository"),
  DriverRepository: Symbol.for("DriverRepository"),
  MaintenanceRepository: Symbol.for("MaintenanceRepository"),
  FacilityRepository: Symbol.for("FacilityRepository"),
  TelemetryRepository: Symbol.for("TelemetryRepository"),
  WorkOrderRepository: Symbol.for("WorkOrderRepository"),
  IncidentRepository: Symbol.for("IncidentRepository"),
  InspectionRepository: Symbol.for("InspectionRepository"),
  DocumentRepository: Symbol.for("DocumentRepository"),
  CommunicationRepository: Symbol.for("CommunicationRepository"),
  BreakGlassRepository: Symbol.for("BreakGlassRepository"),
  GeofenceRepository: Symbol.for("GeofenceRepository"),
  VideoEventRepository: Symbol.for("VideoEventRepository"),
  SyncRepository: Symbol.for("SyncRepository"),
  TripRepository: Symbol.for("TripRepository"),
  TripUsageRepository: Symbol.for("TripUsageRepository"),
  PersonalUsePolicyRepository: Symbol.for("PersonalUsePolicyRepository"),
  ReimbursementRequestRepository: Symbol.for("ReimbursementRequestRepository"),
  HealthCheckRepository: Symbol.for("HealthCheckRepository"),
  RouteRepository: Symbol.for("RouteRepository"),
  PermissionRepository: Symbol.for("PermissionRepository"),
  VehicleAssignmentRepository: Symbol.for("VehicleAssignmentRepository"),
  ReservationRepository: Symbol.for("ReservationRepository"),
};
