export const TYPES = {
  // Controllers
  VehicleController: Symbol.for("VehicleController"),
  DriverController: Symbol.for("DriverController"),
  MaintenanceController: Symbol.for("MaintenanceController"),
  FacilityController: Symbol.for("FacilityController"),
  TelemetryController: Symbol.for("TelemetryController"),
  WorkOrderController: Symbol.for("WorkOrderController"),
  IncidentController: Symbol.for("IncidentController"),
  InspectionController: Symbol.for("InspectionController"),
  DocumentController: Symbol.for("DocumentController"),

  // Services
  VehicleService: Symbol.for("VehicleService"),
  DriverService: Symbol.for("DriverService"),
  MaintenanceService: Symbol.for("MaintenanceService"),
  FacilityService: Symbol.for("FacilityService"),
  TelemetryService: Symbol.for("TelemetryService"),
  WorkOrderService: Symbol.for("WorkOrderService"),
  IncidentService: Symbol.for("IncidentService"),
  InspectionService: Symbol.for("InspectionService"),
  DocumentService: Symbol.for("DocumentService"),

  // Monitoring & Logging Services
  ApplicationInsightsService: Symbol.for("ApplicationInsightsService"),
  CacheService: Symbol.for("CacheService"),
  SentryService: Symbol.for("SentryService"),
  AnalyticsService: Symbol.for("AnalyticsService"),
  NotificationService: Symbol.for("NotificationService"),
  JobQueueService: Symbol.for("JobQueueService"),
  MCPServerService: Symbol.for("MCPServerService"),
  CustomFieldsService: Symbol.for("CustomFieldsService"),
  QueueService: Symbol.for("QueueService"),
  CameraSyncService: Symbol.for("CameraSyncService"),
  EmailNotificationService: Symbol.for("EmailNotificationService"),

  // Business Logic Services (Batch 2)
  SyncService: Symbol.for("SyncService"),
  TeamsService: Symbol.for("TeamsService"),
  OutlookService: Symbol.for("OutlookService"),
  ExcelExportService: Symbol.for("ExcelExportService"),
  AIDispatchService: Symbol.for("AIDispatchService"),
  WebRTCService: Symbol.for("WebRTCService"),
  DocumentRAGService: Symbol.for("DocumentRAGService"),
  DocumentManagementService: Symbol.for("DocumentManagementService"),
  DocumentSearchService: Symbol.for("DocumentSearchService"),
  VectorSearchService: Symbol.for("VectorSearchService"),
  EmbeddingService: Symbol.for("EmbeddingService"),
  SearchIndexService: Symbol.for("SearchIndexService"),
  DocumentAuditService: Symbol.for("DocumentAuditService"),
  DocumentVersionService: Symbol.for("DocumentVersionService"),
  DocumentStorageService: Symbol.for("DocumentStorageService"),
  RouteOptimizationService: Symbol.for("RouteOptimizationService"),
  DriverScorecardService: Symbol.for("DriverScorecardService"),
  VehicleIdentificationService: Symbol.for("VehicleIdentificationService"),
  FuelPurchasingService: Symbol.for("FuelPurchasingService"),
  CostAnalysisService: Symbol.for("CostAnalysisService"),
  FleetOptimizerService: Symbol.for("FleetOptimizerService"),
  ExecutiveDashboardService: Symbol.for("ExecutiveDashboardService"),

  // Repositories
  VehicleRepository: Symbol.for("VehicleRepository"),
  DriverRepository: Symbol.for("DriverRepository"),
  MaintenanceRepository: Symbol.for("MaintenanceRepository"),
  FacilityRepository: Symbol.for("FacilityRepository"),
  TelemetryRepository: Symbol.for("TelemetryRepository"),
  WorkOrderRepository: Symbol.for("WorkOrderRepository"),
  IncidentRepository: Symbol.for("IncidentRepository"),
  InspectionRepository: Symbol.for("InspectionRepository"),
  DocumentRepository: Symbol.for("DocumentRepository"),
  CommunicationRepository: Symbol.for("CommunicationRepository"),
  BreakGlassRepository: Symbol.for("BreakGlassRepository"),
  GeofenceRepository: Symbol.for("GeofenceRepository"),
  VideoEventRepository: Symbol.for("VideoEventRepository"),
  SyncRepository: Symbol.for("SyncRepository"),
  TripRepository: Symbol.for("TripRepository"),
  TripUsageRepository: Symbol.for("TripUsageRepository"),
  PersonalUsePolicyRepository: Symbol.for("PersonalUsePolicyRepository"),
  ReimbursementRequestRepository: Symbol.for("ReimbursementRequestRepository"),
  HealthCheckRepository: Symbol.for("HealthCheckRepository"),
  RouteRepository: Symbol.for("RouteRepository"),
  PermissionRepository: Symbol.for("PermissionRepository"),
  VehicleAssignmentRepository: Symbol.for("VehicleAssignmentRepository"),
  ReservationRepository: Symbol.for("ReservationRepository"),
  TelematicsRepository: Symbol.for("TelematicsRepository"),
  DamageReportRepository: Symbol.for("DamageReportRepository"),

  // Additional Core Repositories
  AlertRepository: Symbol.for("AlertRepository"),
  AttachmentRepository: Symbol.for("AttachmentRepository"),
  ChargingSessionRepository: Symbol.for("ChargingSessionRepository"),
  ChargingStationRepository: Symbol.for("ChargingStationRepository"),
  CostRepository: Symbol.for("CostRepository"),
  DeploymentRepository: Symbol.for("DeploymentRepository"),
  FuelRepository: Symbol.for("FuelRepository"),
  InvoiceRepository: Symbol.for("InvoiceRepository"),
  PartRepository: Symbol.for("PartRepository"),
  PolicyRepository: Symbol.for("PolicyRepository"),
  PurchaseOrderRepository: Symbol.for("PurchaseOrderRepository"),
  ReimbursementRepository: Symbol.for("ReimbursementRepository"),
  TaskRepository: Symbol.for("TaskRepository"),
  VendorRepository: Symbol.for("VendorRepository"),
};
