# SwiftLint Configuration for Fleet Management iOS App

# Paths to include/exclude from linting
included:
  - App
  - AppTests

excluded:
  - Pods
  - DerivedData
  - .build

# Disable specific rules
disabled_rules:
  - trailing_whitespace
  - todo
  - large_tuple
  - function_parameter_count

# Opt-in rules
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - contains_over_first_not_nil
  - sorted_first_last
  - closure_spacing
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - db
    - os

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(\bprint\s*\()'
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_cast:
    name: "No Force Casting"
    regex: '(as!)'
    message: "Use safe casting with as? instead"
    severity: error

# Reporter format
reporter: "xcode"
