#!/bin/bash
# Script to add missing files to Xcode project
# Note: This is a reference script. The easiest way is to add files manually in Xcode.

echo "Files that need to be added to App.xcodeproj:"
echo ""
echo "1. App/CrashReporter.swift"
echo "2. App/AuthenticationService.swift"
echo "3. App/SyncService.swift"
echo "4. App/NetworkMonitor.swift"
echo "5. App/TripModels.swift"
echo "6. App/ViewModels/VehicleViewModel.swift"
echo ""
echo "These files exist in the filesystem but are not included in the Xcode project."
echo ""
echo "MANUAL STEPS IN XCODE:"
echo "====================="
echo ""
echo "1. CLOSE Xcode if it's currently open"
echo ""
echo "2. OPEN the WORKSPACE instead of the project:"
echo "   open App.xcworkspace"
echo "   (NOT App.xcodeproj - you need the workspace for CocoaPods)"
echo ""
echo "3. In Xcode, right-click on the 'App' folder in Project Navigator"
echo ""
echo "4. Select 'Add Files to \"App\"...'"
echo ""
echo "5. Navigate to /Users/andrewmorton/Documents/GitHub/Fleet/mobile-apps/ios-native/App/"
echo ""
echo "6. Multi-select these files (hold ⌘ key):"
echo "   - CrashReporter.swift"
echo "   - AuthenticationService.swift"
echo "   - SyncService.swift"
echo "   - NetworkMonitor.swift"
echo "   - TripModels.swift"
echo ""
echo "7. Also add from ViewModels/ folder:"
echo "   - ViewModels/VehicleViewModel.swift"
echo ""
echo "8. IMPORTANT settings when adding:"
echo "   ✅ 'App' target is CHECKED"
echo "   ❌ 'Copy items if needed' is UNCHECKED"
echo "   ✅ 'Create groups' is selected"
echo ""
echo "9. Click 'Add'"
echo ""
echo "10. Build the project: ⌘+B"
echo ""
echo "After adding these files, all 'Cannot find' errors should be resolved!"
