"use strict";
// Complete Drizzle ORM Schema for Fleet Local
Object.defineProperty(exports, "__esModule", { value: true });
exports.sessions = exports.users = exports.vehicle3dModels = exports.facilities = exports.vendors = exports.parts = exports.incidents = exports.maintenanceRecords = exports.fuelTransactions = exports.drivers = exports.vehicles = void 0;
const pg_core_1 = require("drizzle-orm/pg-core");
// Vehicles table
exports.vehicles = (0, pg_core_1.pgTable)('vehicles', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    vehicleNumber: (0, pg_core_1.varchar)('vehicle_number', { length: 50 }).notNull().unique(),
    make: (0, pg_core_1.varchar)('make', { length: 100 }).notNull(),
    model: (0, pg_core_1.varchar)('model', { length: 100 }).notNull(),
    year: (0, pg_core_1.integer)('year').notNull(),
    vin: (0, pg_core_1.varchar)('vin', { length: 17 }).notNull().unique(),
    licensePlate: (0, pg_core_1.varchar)('license_plate', { length: 20 }).notNull(),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).notNull().default('active'),
    mileage: (0, pg_core_1.integer)('mileage').notNull().default(0),
    fuelType: (0, pg_core_1.varchar)('fuel_type', { length: 50 }).notNull(),
    location: (0, pg_core_1.varchar)('location', { length: 255 }),
    assignedDriverId: (0, pg_core_1.integer)('assigned_driver_id'),
    facilityId: (0, pg_core_1.integer)('facility_id'),
    model3dId: (0, pg_core_1.integer)('model_3d_id'),
    lastServiceDate: (0, pg_core_1.timestamp)('last_service_date'),
    nextServiceDate: (0, pg_core_1.timestamp)('next_service_date'),
    purchaseDate: (0, pg_core_1.timestamp)('purchase_date'),
    purchasePrice: (0, pg_core_1.decimal)('purchase_price', { precision: 10, scale: 2 }),
    currentValue: (0, pg_core_1.decimal)('current_value', { precision: 10, scale: 2 }),
    insurancePolicyNumber: (0, pg_core_1.varchar)('insurance_policy_number', { length: 100 }),
    registrationExpiry: (0, pg_core_1.timestamp)('registration_expiry'),
    inspectionDue: (0, pg_core_1.timestamp)('inspection_due'),
    specifications: (0, pg_core_1.jsonb)('specifications'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// Drivers table
exports.drivers = (0, pg_core_1.pgTable)('drivers', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    employeeId: (0, pg_core_1.varchar)('employee_id', { length: 50 }).unique(),
    name: (0, pg_core_1.varchar)('name', { length: 255 }).notNull(),
    email: (0, pg_core_1.varchar)('email', { length: 255 }).notNull().unique(),
    phone: (0, pg_core_1.varchar)('phone', { length: 20 }),
    licenseNumber: (0, pg_core_1.varchar)('license_number', { length: 50 }).notNull().unique(),
    licenseExpiry: (0, pg_core_1.timestamp)('license_expiry').notNull(),
    licenseClass: (0, pg_core_1.varchar)('license_class', { length: 10 }),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).notNull().default('active'),
    photoUrl: (0, pg_core_1.varchar)('photo_url', { length: 500 }),
    azureAdId: (0, pg_core_1.varchar)('azure_ad_id', { length: 255 }),
    assignedVehicleId: (0, pg_core_1.integer)('assigned_vehicle_id'),
    rating: (0, pg_core_1.decimal)('rating', { precision: 3, scale: 2 }).default('5.00'),
    totalTrips: (0, pg_core_1.integer)('total_trips').default(0),
    totalMiles: (0, pg_core_1.integer)('total_miles').default(0),
    safetyScore: (0, pg_core_1.integer)('safety_score').default(100),
    hireDate: (0, pg_core_1.timestamp)('hire_date'),
    certifications: (0, pg_core_1.jsonb)('certifications'),
    emergencyContact: (0, pg_core_1.jsonb)('emergency_contact'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// Fuel Transactions
exports.fuelTransactions = (0, pg_core_1.pgTable)('fuel_transactions', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    vehicleId: (0, pg_core_1.integer)('vehicle_id').notNull(),
    driverId: (0, pg_core_1.integer)('driver_id'),
    vehicleNumber: (0, pg_core_1.varchar)('vehicle_number', { length: 50 }).notNull(),
    date: (0, pg_core_1.timestamp)('date').notNull().defaultNow(),
    station: (0, pg_core_1.varchar)('station', { length: 255 }).notNull(),
    gallons: (0, pg_core_1.decimal)('gallons', { precision: 6, scale: 2 }).notNull(),
    pricePerGallon: (0, pg_core_1.decimal)('price_per_gallon', { precision: 5, scale: 3 }).notNull(),
    totalCost: (0, pg_core_1.decimal)('total_cost', { precision: 8, scale: 2 }).notNull(),
    mpg: (0, pg_core_1.decimal)('mpg', { precision: 5, scale: 2 }),
    odometerReading: (0, pg_core_1.integer)('odometer_reading'),
    paymentMethod: (0, pg_core_1.varchar)('payment_method', { length: 50 }),
    receiptUrl: (0, pg_core_1.varchar)('receipt_url', { length: 500 }),
    notes: (0, pg_core_1.text)('notes'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
});
// Maintenance Records
exports.maintenanceRecords = (0, pg_core_1.pgTable)('maintenance_records', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    vehicleId: (0, pg_core_1.integer)('vehicle_id').notNull(),
    vehicleNumber: (0, pg_core_1.varchar)('vehicle_number', { length: 50 }).notNull(),
    serviceType: (0, pg_core_1.varchar)('service_type', { length: 100 }).notNull(),
    serviceDate: (0, pg_core_1.timestamp)('service_date').notNull(),
    nextDue: (0, pg_core_1.timestamp)('next_due'),
    mileageAtService: (0, pg_core_1.integer)('mileage_at_service'),
    nextDueMileage: (0, pg_core_1.integer)('next_due_mileage'),
    priority: (0, pg_core_1.varchar)('priority', { length: 20 }).default('medium'),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).default('scheduled'),
    estimatedCost: (0, pg_core_1.decimal)('estimated_cost', { precision: 8, scale: 2 }),
    actualCost: (0, pg_core_1.decimal)('actual_cost', { precision: 8, scale: 2 }),
    vendor: (0, pg_core_1.varchar)('vendor', { length: 255 }),
    technicianName: (0, pg_core_1.varchar)('technician_name', { length: 255 }),
    partsReplaced: (0, pg_core_1.jsonb)('parts_replaced'),
    workPerformed: (0, pg_core_1.text)('work_performed'),
    notes: (0, pg_core_1.text)('notes'),
    invoiceUrl: (0, pg_core_1.varchar)('invoice_url', { length: 500 }),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// Additional tables (compact)
exports.incidents = (0, pg_core_1.pgTable)('incidents', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    vehicleId: (0, pg_core_1.integer)('vehicle_id').notNull(),
    driverId: (0, pg_core_1.integer)('driver_id'),
    incidentDate: (0, pg_core_1.timestamp)('incident_date').notNull(),
    type: (0, pg_core_1.varchar)('type', { length: 50 }).notNull(),
    severity: (0, pg_core_1.varchar)('severity', { length: 20 }).notNull(),
    description: (0, pg_core_1.text)('description').notNull(),
    location: (0, pg_core_1.varchar)('location', { length: 255 }),
    damageEstimate: (0, pg_core_1.decimal)('damage_estimate', { precision: 10, scale: 2 }),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).default('open'),
    reportedBy: (0, pg_core_1.varchar)('reported_by', { length: 255 }),
    photos: (0, pg_core_1.jsonb)('photos'),
    witnesses: (0, pg_core_1.jsonb)('witnesses'),
    policeReportNumber: (0, pg_core_1.varchar)('police_report_number', { length: 100 }),
    insuranceClaimNumber: (0, pg_core_1.varchar)('insurance_claim_number', { length: 100 }),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
});
exports.parts = (0, pg_core_1.pgTable)('parts', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    partNumber: (0, pg_core_1.varchar)('part_number', { length: 100 }).notNull().unique(),
    name: (0, pg_core_1.varchar)('name', { length: 255 }).notNull(),
    description: (0, pg_core_1.text)('description'),
    category: (0, pg_core_1.varchar)('category', { length: 100 }),
    manufacturer: (0, pg_core_1.varchar)('manufacturer', { length: 255 }),
    quantityInStock: (0, pg_core_1.integer)('quantity_in_stock').notNull().default(0),
    minimumStock: (0, pg_core_1.integer)('minimum_stock').default(10),
    unitCost: (0, pg_core_1.decimal)('unit_cost', { precision: 10, scale: 2 }).notNull(),
    vendorId: (0, pg_core_1.integer)('vendor_id'),
    location: (0, pg_core_1.varchar)('location', { length: 255 }),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
});
exports.vendors = (0, pg_core_1.pgTable)('vendors', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    name: (0, pg_core_1.varchar)('name', { length: 255 }).notNull(),
    type: (0, pg_core_1.varchar)('type', { length: 100 }).notNull(),
    contactName: (0, pg_core_1.varchar)('contact_name', { length: 255 }),
    email: (0, pg_core_1.varchar)('email', { length: 255 }),
    phone: (0, pg_core_1.varchar)('phone', { length: 20 }),
    address: (0, pg_core_1.text)('address'),
    rating: (0, pg_core_1.decimal)('rating', { precision: 3, scale: 2 }),
    contractNumber: (0, pg_core_1.varchar)('contract_number', { length: 100 }),
    contractExpiry: (0, pg_core_1.timestamp)('contract_expiry'),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).default('active'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
});
// Facilities table
exports.facilities = (0, pg_core_1.pgTable)('facilities', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    name: (0, pg_core_1.varchar)('name', { length: 255 }).notNull(),
    type: (0, pg_core_1.varchar)('type', { length: 100 }),
    address: (0, pg_core_1.text)('address'),
    city: (0, pg_core_1.varchar)('city', { length: 100 }),
    state: (0, pg_core_1.varchar)('state', { length: 50 }),
    zipCode: (0, pg_core_1.varchar)('zip_code', { length: 20 }),
    phone: (0, pg_core_1.varchar)('phone', { length: 20 }),
    email: (0, pg_core_1.varchar)('email', { length: 255 }),
    capacity: (0, pg_core_1.integer)('capacity'),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).default('active'),
    coordinates: (0, pg_core_1.jsonb)('coordinates'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// 3D Vehicle Models table
exports.vehicle3dModels = (0, pg_core_1.pgTable)('vehicle_3d_models', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    name: (0, pg_core_1.varchar)('name', { length: 255 }).notNull(),
    description: (0, pg_core_1.text)('description'),
    vehicleType: (0, pg_core_1.varchar)('vehicle_type', { length: 100 }),
    make: (0, pg_core_1.varchar)('make', { length: 100 }),
    model: (0, pg_core_1.varchar)('model', { length: 100 }),
    year: (0, pg_core_1.integer)('year'),
    fileUrl: (0, pg_core_1.varchar)('file_url', { length: 500 }).notNull(),
    fileFormat: (0, pg_core_1.varchar)('file_format', { length: 20 }),
    fileSizeMb: (0, pg_core_1.decimal)('file_size_mb', { precision: 8, scale: 2 }),
    polyCount: (0, pg_core_1.integer)('poly_count'),
    source: (0, pg_core_1.varchar)('source', { length: 50 }),
    sourceId: (0, pg_core_1.varchar)('source_id', { length: 255 }),
    license: (0, pg_core_1.varchar)('license', { length: 100 }),
    licenseUrl: (0, pg_core_1.varchar)('license_url', { length: 500 }),
    author: (0, pg_core_1.varchar)('author', { length: 255 }),
    authorUrl: (0, pg_core_1.varchar)('author_url', { length: 500 }),
    thumbnailUrl: (0, pg_core_1.varchar)('thumbnail_url', { length: 500 }),
    previewImages: (0, pg_core_1.jsonb)('preview_images'),
    qualityTier: (0, pg_core_1.varchar)('quality_tier', { length: 20 }),
    hasInterior: (0, pg_core_1.boolean)('has_interior').default(false),
    hasPbrMaterials: (0, pg_core_1.boolean)('has_pbr_materials').default(false),
    viewCount: (0, pg_core_1.integer)('view_count').default(0),
    downloadCount: (0, pg_core_1.integer)('download_count').default(0),
    isFeatured: (0, pg_core_1.boolean)('is_featured').default(false),
    isActive: (0, pg_core_1.boolean)('is_active').default(true),
    tags: (0, pg_core_1.jsonb)('tags'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// Users table (for authentication)
exports.users = (0, pg_core_1.pgTable)('users', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    email: (0, pg_core_1.varchar)('email', { length: 255 }).notNull().unique(),
    microsoftId: (0, pg_core_1.varchar)('microsoft_id', { length: 255 }).unique(),
    displayName: (0, pg_core_1.varchar)('display_name', { length: 255 }),
    role: (0, pg_core_1.varchar)('role', { length: 50 }).default('user'),
    authProvider: (0, pg_core_1.varchar)('auth_provider', { length: 50 }).default('microsoft'),
    isActive: (0, pg_core_1.boolean)('is_active').default(true),
    lastLoginAt: (0, pg_core_1.timestamp)('last_login_at'),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)('updated_at').defaultNow(),
});
// Sessions table (for authentication)
exports.sessions = (0, pg_core_1.pgTable)('sessions', {
    id: (0, pg_core_1.serial)('id').primaryKey(),
    userId: (0, pg_core_1.integer)('user_id').notNull(),
    token: (0, pg_core_1.varchar)('token', { length: 500 }).notNull().unique(),
    expiresAt: (0, pg_core_1.timestamp)('expires_at').notNull(),
    createdAt: (0, pg_core_1.timestamp)('created_at').defaultNow(),
});
console.log("Complete database schema with 13+ tables created");
//# sourceMappingURL=schema.js.map